export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const REMOVE_TRANSACTION = "REMOVE_TRANSACTION";
export const LOCAL_STORAGE_DATA = "LOCAL_STORAGE_DATA";
export const ADD_DB_DATA = "ADD_DB_DATA";
